'use client'
export default function Head() {
    return (
        <>
            <title>MedsCred</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/public/assets/images/favicon.png" />
        </>
    );
}
